"""Builds the Firebase password-reset email templates (en + ar).

Run:  python3 email_templates/build.py
Then paste each generated file into Firebase console >
Authentication > Templates > Password reset > Message.
Firebase fills %LINK%, %EMAIL%, %APP_NAME% at send time.
"""
from pathlib import Path

BASE = "https://push-notification-1cf6d.web.app"
OUT = Path(__file__).parent

T = {
    "en": dict(
        dir="ltr", align="left",
        font="'Cairo','Segoe UI',Roboto,Helvetica,Arial,sans-serif",
        tagline="Every pound, in its place.",
        title="Forgot your password? No worries 👋",
        body="We got a request to reset the password for your Flowsy account "
             "<b style=\"color:#1A1C1E\">%EMAIL%</b>. Tap the button below to pick a new one "
             "and get back to your wallets.",
        cta="Reset my password",
        expires="⏱ This link expires in 1 hour",
        fallback="Button not working? Copy and paste this link into your browser:",
        safe_title="Didn't ask for this?",
        safe="Just ignore this email. Your password stays the same and your wallets stay safe.",
        footer="You're receiving this because a password reset was requested for your Flowsy account.",
        privacy="Privacy policy",
        hero_alt="Your Flowsy wallet, safely locked",
    ),
    "ar": dict(
        dir="rtl", align="right",
        font="'Cairo','Segoe UI',Tahoma,Arial,sans-serif",
        tagline="كل جنيه في مكانه.",
        title="نسيت كلمة السر؟ ولا يهمك 👋",
        body="وصلنا طلب لإعادة تعيين كلمة السر لحسابك على Flowsy "
             "<b style=\"color:#1A1C1E\" dir=\"ltr\">%EMAIL%</b>. دوس على الزرار تحت واختار كلمة سر جديدة "
             "وارجع لمحافظك على طول.",
        cta="غيّر كلمة السر",
        expires="⏱ اللينك ده صالح لمدة ساعة واحدة",
        fallback="الزرار مش شغال؟ انسخ اللينك ده وافتحه في المتصفح:",
        safe_title="مش إنت اللي طلبت ده؟",
        safe="تجاهل الإيميل ده عادي. كلمة السر بتاعتك زي ما هي ومحافظك في أمان.",
        footer="الإيميل ده وصلك لأن حد طلب إعادة تعيين كلمة السر لحسابك على Flowsy.",
        privacy="سياسة الخصوصية",
        hero_alt="محفظتك على Flowsy في أمان",
    ),
}

TEMPLATE = """<!-- Flowsy password reset ({lang}). Generated by email_templates/build.py -->
<div dir="{dir}" style="margin:0;padding:0;background:#EEF5F0;font-family:{font};">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#EEF5F0;">
<tr><td align="center" style="padding:28px 12px;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="max-width:560px;">

  <!-- brand row -->
  <tr><td align="center" style="padding:0 0 18px;">
    <table role="presentation" cellpadding="0" cellspacing="0" border="0"><tr>
      <td style="padding:0 8px;"><img src="{base}/email/logo.png" width="40" height="40" alt="Flowsy" style="display:block;border:0;border-radius:10px;"></td>
      <td style="padding:0 8px;font-size:22px;font-weight:800;color:#0B8A4C;letter-spacing:.3px;">Flowsy</td>
    </tr></table>
  </td></tr>

  <!-- card -->
  <tr><td style="background:#FFFFFF;border-radius:24px;overflow:hidden;box-shadow:0 10px 30px rgba(8,122,67,.12);">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
      <tr><td style="background:#0EA05A;border-radius:24px 24px 0 0;line-height:0;font-size:0;">
        <img src="{base}/email/reset-hero.png" width="560" alt="{hero_alt}" style="display:block;width:100%;max-width:560px;height:auto;border:0;border-radius:24px 24px 0 0;">
      </td></tr>

      <tr><td style="padding:32px 32px 8px;text-align:{align};">
        <h1 style="margin:0 0 12px;font-size:24px;line-height:1.35;color:#1A1C1E;font-weight:800;">{title}</h1>
        <p style="margin:0;font-size:16px;line-height:1.75;color:#44474E;">{body}</p>
      </td></tr>

      <!-- button -->
      <tr><td align="center" style="padding:26px 32px 10px;">
        <table role="presentation" cellpadding="0" cellspacing="0" border="0"><tr>
          <td align="center" style="border-radius:14px;background:#0EA05A;background-image:linear-gradient(135deg,#16B866,#087A43);box-shadow:0 6px 16px rgba(14,160,90,.35);">
            <a href="%LINK%" target="_blank" style="display:inline-block;padding:15px 38px;font-size:17px;font-weight:700;color:#FFFFFF;text-decoration:none;border-radius:14px;">{cta}</a>
          </td>
        </tr></table>
      </td></tr>

      <!-- expiry chip -->
      <tr><td align="center" style="padding:8px 32px 24px;">
        <span style="display:inline-block;background:#FFF6D6;color:#8A6400;font-size:13px;font-weight:600;padding:6px 14px;border-radius:999px;">{expires}</span>
      </td></tr>

      <!-- security note -->
      <tr><td style="padding:0 32px 24px;">
        <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#F1F8F4;border-radius:16px;">
          <tr><td style="padding:16px 18px;text-align:{align};">
            <p style="margin:0 0 4px;font-size:14px;font-weight:700;color:#0B8A4C;">🔒 {safe_title}</p>
            <p style="margin:0;font-size:14px;line-height:1.6;color:#44474E;">{safe}</p>
          </td></tr>
        </table>
      </td></tr>

      <!-- fallback link -->
      <tr><td style="padding:0 32px 30px;text-align:{align};">
        <p style="margin:0 0 6px;font-size:12px;color:#757575;">{fallback}</p>
        <p dir="ltr" style="margin:0;font-size:12px;line-height:1.5;word-break:break-all;text-align:left;"><a href="%LINK%" style="color:#0EA05A;">%LINK%</a></p>
      </td></tr>
    </table>
  </td></tr>

  <!-- footer -->
  <tr><td align="center" style="padding:22px 24px 0;">
    <p style="margin:0 0 6px;font-size:15px;font-weight:700;color:#0B8A4C;">{tagline}</p>
    <p style="margin:0 0 8px;font-size:12px;line-height:1.6;color:#757575;">{footer}</p>
    <p style="margin:0;font-size:12px;"><a href="{base}/privacy" style="color:#0EA05A;text-decoration:none;">{privacy}</a> &nbsp;·&nbsp; <span style="color:#9E9E9E;">© Flowsy</span></p>
  </td></tr>

</table>
</td></tr>
</table>
</div>
"""

for lang, t in T.items():
    html = TEMPLATE.format(lang=lang, base=BASE, **t)
    (OUT / f"reset-password.{lang}.html").write_text(html, encoding="utf-8")
    # Preview with sample values so it can be opened in a browser.
    preview = (html.replace("%LINK%", f"{BASE}/__/auth/action?mode=resetPassword&oobCode=SAMPLE")
                   .replace("%EMAIL%", "salma@example.com").replace("%APP_NAME%", "Flowsy"))
    (OUT / f"preview.{lang}.html").write_text(
        f'<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">'
        f'<link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700;800&display=swap" rel="stylesheet">'
        f'<body style="margin:0">{preview}', encoding="utf-8")
    print("wrote", lang)
