// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// PLACEHOLDER — this file has NOT been generated by `flutterfire configure` yet.
///
/// The values below are fake and will make `Firebase.initializeApp()` fail at
/// runtime with an invalid-api-key error. The app still compiles and
/// `flutter analyze` stays clean with this file in place.
///
/// To make Firebase actually work:
///   1. Create (or choose) a Firebase project: `firebase projects:create` or
///      https://console.firebase.google.com
///   2. From this project's root, run:
///        flutterfire configure --project=<your-project-id> --platforms=android,ios -y
///      This OVERWRITES this file with real options and registers Android/iOS
///      apps in that Firebase project automatically.
///   3. Deploy the Firestore security rules in `firestore.rules` (see the repo
///      root) with: `firebase deploy --only firestore:rules` (after
///      `firebase init firestore` to link this folder to the project, or by
///      pasting the rules into the Firebase console's Firestore Rules tab).
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    iosBundleId: 'com.example.walletSplit',
  );
}
